services:
  bot:
    image: ghcr.io/soni801/soni-bot:latest
    # Use environment values from the .env file.
    # If you don't want this, comment the following line and use the individual environment variables below instead.
    env_file: '.env.production'
    #environment:
    #  TOKEN: changeme
    #  DB_HOST: db
    #  DB_USER: soni_bot
    #  DB_PASS: changeme
    #  DB_NAME: soni_bot
    restart: unless-stopped
  db:
    image: postgres
    restart: always
    shm_size: 128mb # Set shared memory limit when using docker-compose
    environment:
      POSTGRES_USER: soni_bot
      POSTGRES_PASSWORD: changeme
